default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1

development:
  <<: *default
  database: Strawpoll_development
  username: <%= ENV['STRAWPOLL_DATABASE_USERNAME'] %>
  password: <%= ENV['STRAWPOLL_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: Strawpoll_test
  username: <%= ENV['STRAWPOLL_DATABASE_USERNAME'] %>
  password: <%= ENV['STRAWPOLL_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: Strawpoll_production
  username: <%= ENV['STRAWPOLL_DATABASE_USERNAME'] %>
  password: <%= ENV['STRAWPOLL_DATABASE_PASSWORD'] %>
